// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: common/position.proto

package trade

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PositionDirection_Enum int32

const (
	// 未知
	PositionDirection_UnKnow PositionDirection_Enum = 0
	// 多头持仓
	PositionDirection_LONG PositionDirection_Enum = 1
	// 空头
	PositionDirection_SHORT PositionDirection_Enum = 2
)

// Enum value maps for PositionDirection_Enum.
var (
	PositionDirection_Enum_name = map[int32]string{
		0: "UnKnow",
		1: "LONG",
		2: "SHORT",
	}
	PositionDirection_Enum_value = map[string]int32{
		"UnKnow": 0,
		"LONG":   1,
		"SHORT":  2,
	}
)

func (x PositionDirection_Enum) Enum() *PositionDirection_Enum {
	p := new(PositionDirection_Enum)
	*p = x
	return p
}

func (x PositionDirection_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PositionDirection_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_common_position_proto_enumTypes[0].Descriptor()
}

func (PositionDirection_Enum) Type() protoreflect.EnumType {
	return &file_common_position_proto_enumTypes[0]
}

func (x PositionDirection_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PositionDirection_Enum.Descriptor instead.
func (PositionDirection_Enum) EnumDescriptor() ([]byte, []int) {
	return file_common_position_proto_rawDescGZIP(), []int{4, 0}
}

type PositionChannel_Enum int32

const (
	//
	PositionChannel_UnKnow  PositionChannel_Enum = 0
	PositionChannel_CONNECT PositionChannel_Enum = 1
	PositionChannel_QFII    PositionChannel_Enum = 2
	// INNER
	PositionChannel_INNER PositionChannel_Enum = 3
)

// Enum value maps for PositionChannel_Enum.
var (
	PositionChannel_Enum_name = map[int32]string{
		0: "UnKnow",
		1: "CONNECT",
		2: "QFII",
		3: "INNER",
	}
	PositionChannel_Enum_value = map[string]int32{
		"UnKnow":  0,
		"CONNECT": 1,
		"QFII":    2,
		"INNER":   3,
	}
)

func (x PositionChannel_Enum) Enum() *PositionChannel_Enum {
	p := new(PositionChannel_Enum)
	*p = x
	return p
}

func (x PositionChannel_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PositionChannel_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_common_position_proto_enumTypes[1].Descriptor()
}

func (PositionChannel_Enum) Type() protoreflect.EnumType {
	return &file_common_position_proto_enumTypes[1]
}

func (x PositionChannel_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PositionChannel_Enum.Descriptor instead.
func (PositionChannel_Enum) EnumDescriptor() ([]byte, []int) {
	return file_common_position_proto_rawDescGZIP(), []int{5, 0}
}

// 查询持仓请求
type GetPositionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 资金账号
	AccountId string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	// 证券代码
	Symbol string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 持仓方向
	PositionDirection PositionDirection_Enum `protobuf:"varint,3,opt,name=positionDirection,proto3,enum=pb.PositionDirection_Enum" json:"positionDirection,omitempty"`
}

func (x *GetPositionRequest) Reset() {
	*x = GetPositionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_position_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionRequest) ProtoMessage() {}

func (x *GetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_position_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionRequest.ProtoReflect.Descriptor instead.
func (*GetPositionRequest) Descriptor() ([]byte, []int) {
	return file_common_position_proto_rawDescGZIP(), []int{0}
}

func (x *GetPositionRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetPositionRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetPositionRequest) GetPositionDirection() PositionDirection_Enum {
	if x != nil {
		return x.PositionDirection
	}
	return PositionDirection_UnKnow
}

// 查询持仓应答
type GetPositionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorId   int32       `protobuf:"varint,1,opt,name=errorId,proto3" json:"errorId,omitempty"`
	ErrorMsg  string      `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	Positions []*Position `protobuf:"bytes,3,rep,name=positions,proto3" json:"positions,omitempty"`
}

func (x *GetPositionReply) Reset() {
	*x = GetPositionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_position_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPositionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionReply) ProtoMessage() {}

func (x *GetPositionReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_position_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionReply.ProtoReflect.Descriptor instead.
func (*GetPositionReply) Descriptor() ([]byte, []int) {
	return file_common_position_proto_rawDescGZIP(), []int{1}
}

func (x *GetPositionReply) GetErrorId() int32 {
	if x != nil {
		return x.ErrorId
	}
	return 0
}

func (x *GetPositionReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *GetPositionReply) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

// 查询策略持仓请求
type GetStrategyPositionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 资金账号
	AccountId string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	// 证券代码
	Symbol string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 持仓方向
	PositionDirection PositionDirection_Enum `protobuf:"varint,3,opt,name=positionDirection,proto3,enum=pb.PositionDirection_Enum" json:"positionDirection,omitempty"`
	// 策略编号
	StrategyId string `protobuf:"bytes,4,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
}

func (x *GetStrategyPositionRequest) Reset() {
	*x = GetStrategyPositionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_position_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStrategyPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrategyPositionRequest) ProtoMessage() {}

func (x *GetStrategyPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_position_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategyPositionRequest.ProtoReflect.Descriptor instead.
func (*GetStrategyPositionRequest) Descriptor() ([]byte, []int) {
	return file_common_position_proto_rawDescGZIP(), []int{2}
}

func (x *GetStrategyPositionRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetStrategyPositionRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetStrategyPositionRequest) GetPositionDirection() PositionDirection_Enum {
	if x != nil {
		return x.PositionDirection
	}
	return PositionDirection_UnKnow
}

func (x *GetStrategyPositionRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

// 查询策略持仓应答
type GetStrategyPositionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorId    int32       `protobuf:"varint,1,opt,name=errorId,proto3" json:"errorId,omitempty"`
	ErrorMsg   string      `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	StrategyId string      `protobuf:"bytes,3,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	Positions  []*Position `protobuf:"bytes,4,rep,name=positions,proto3" json:"positions,omitempty"`
}

func (x *GetStrategyPositionReply) Reset() {
	*x = GetStrategyPositionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_position_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStrategyPositionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrategyPositionReply) ProtoMessage() {}

func (x *GetStrategyPositionReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_position_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategyPositionReply.ProtoReflect.Descriptor instead.
func (*GetStrategyPositionReply) Descriptor() ([]byte, []int) {
	return file_common_position_proto_rawDescGZIP(), []int{3}
}

func (x *GetStrategyPositionReply) GetErrorId() int32 {
	if x != nil {
		return x.ErrorId
	}
	return 0
}

func (x *GetStrategyPositionReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *GetStrategyPositionReply) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *GetStrategyPositionReply) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

// 持仓方向
type PositionDirection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PositionDirection) Reset() {
	*x = PositionDirection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_position_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionDirection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionDirection) ProtoMessage() {}

func (x *PositionDirection) ProtoReflect() protoreflect.Message {
	mi := &file_common_position_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionDirection.ProtoReflect.Descriptor instead.
func (*PositionDirection) Descriptor() ([]byte, []int) {
	return file_common_position_proto_rawDescGZIP(), []int{4}
}

// 持仓通道
type PositionChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PositionChannel) Reset() {
	*x = PositionChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_position_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionChannel) ProtoMessage() {}

func (x *PositionChannel) ProtoReflect() protoreflect.Message {
	mi := &file_common_position_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionChannel.ProtoReflect.Descriptor instead.
func (*PositionChannel) Descriptor() ([]byte, []int) {
	return file_common_position_proto_rawDescGZIP(), []int{5}
}

// 仓位
type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 仓位的：昨日数量
	YesterdayVol int32 `protobuf:"varint,1,opt,name=yesterdayVol,proto3" json:"yesterdayVol,omitempty"`
	// 仓位的：今日数量
	TodayVol int32 `protobuf:"varint,2,opt,name=todayVol,proto3" json:"todayVol,omitempty"`
	// 占用保证金
	OccupationMargin float64 `protobuf:"fixed64,3,opt,name=occupationMargin,proto3" json:"occupationMargin,omitempty"`
	// 持仓成本
	PositionAvgPrice float64 `protobuf:"fixed64,4,opt,name=positionAvgPrice,proto3" json:"positionAvgPrice,omitempty"`
	// 浮动盈亏：（市值-成本）*数量
	OpenPl float64 `protobuf:"fixed64,5,opt,name=openPl,proto3" json:"openPl,omitempty"`
	// 全部持仓
	AllQuantity int32 `protobuf:"varint,6,opt,name=allQuantity,proto3" json:"allQuantity,omitempty"`
	// 持仓方向
	Direction PositionDirection_Enum `protobuf:"varint,7,opt,name=direction,proto3,enum=pb.PositionDirection_Enum" json:"direction,omitempty"`
	// 可卖持仓：对于股票来说：等于昨天的仓位：对于期货来说：等于今天开仓+昨天持仓
	AvailableQuantiy int32 `protobuf:"varint,8,opt,name=availableQuantiy,proto3" json:"availableQuantiy,omitempty"`
	// 合约对象
	Symbol string `protobuf:"bytes,9,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 冻结数量
	FrozenQuantity int32 `protobuf:"varint,10,opt,name=frozenQuantity,proto3" json:"frozenQuantity,omitempty"`
	// 仓位的创建时间
	CreateTime int64 `protobuf:"varint,11,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// 资金账号
	AccountId string `protobuf:"bytes,12,opt,name=accountId,proto3" json:"accountId,omitempty"`
	// 策略编号
	StrategyId string `protobuf:"bytes,13,opt,name=StrategyId,proto3" json:"StrategyId,omitempty"`
	// 通道
	Channel PositionChannel_Enum `protobuf:"varint,14,opt,name=channel,proto3,enum=pb.PositionChannel_Enum" json:"channel,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_position_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_common_position_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_common_position_proto_rawDescGZIP(), []int{6}
}

func (x *Position) GetYesterdayVol() int32 {
	if x != nil {
		return x.YesterdayVol
	}
	return 0
}

func (x *Position) GetTodayVol() int32 {
	if x != nil {
		return x.TodayVol
	}
	return 0
}

func (x *Position) GetOccupationMargin() float64 {
	if x != nil {
		return x.OccupationMargin
	}
	return 0
}

func (x *Position) GetPositionAvgPrice() float64 {
	if x != nil {
		return x.PositionAvgPrice
	}
	return 0
}

func (x *Position) GetOpenPl() float64 {
	if x != nil {
		return x.OpenPl
	}
	return 0
}

func (x *Position) GetAllQuantity() int32 {
	if x != nil {
		return x.AllQuantity
	}
	return 0
}

func (x *Position) GetDirection() PositionDirection_Enum {
	if x != nil {
		return x.Direction
	}
	return PositionDirection_UnKnow
}

func (x *Position) GetAvailableQuantiy() int32 {
	if x != nil {
		return x.AvailableQuantiy
	}
	return 0
}

func (x *Position) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Position) GetFrozenQuantity() int32 {
	if x != nil {
		return x.FrozenQuantity
	}
	return 0
}

func (x *Position) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Position) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Position) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *Position) GetChannel() PositionChannel_Enum {
	if x != nil {
		return x.Channel
	}
	return PositionChannel_UnKnow
}

var File_common_position_proto protoreflect.FileDescriptor

var file_common_position_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x94, 0x01, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x48, 0x0a, 0x11, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52,
	0x11, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x74, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x2a, 0x0a, 0x09,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xbc, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x48, 0x0a,
	0x11, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x45, 0x6e, 0x75, 0x6d, 0x52, 0x11, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x67, 0x79, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x22, 0x9c, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x09, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x3c, 0x0a, 0x11, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x04, 0x45,
	0x6e, 0x75, 0x6d, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x6e, 0x4b, 0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x4c, 0x4f, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x48, 0x4f,
	0x52, 0x54, 0x10, 0x02, 0x22, 0x47, 0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x34, 0x0a, 0x04, 0x45, 0x6e, 0x75, 0x6d, 0x12,
	0x0a, 0x0a, 0x06, 0x55, 0x6e, 0x4b, 0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43,
	0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x51, 0x46, 0x49, 0x49,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x4e, 0x45, 0x52, 0x10, 0x03, 0x22, 0x94, 0x04,
	0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x79, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x64, 0x61, 0x79, 0x56, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x79, 0x65, 0x73, 0x74, 0x65, 0x72, 0x64, 0x61, 0x79, 0x56, 0x6f, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x6f, 0x64, 0x61, 0x79, 0x56, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x74, 0x6f, 0x64, 0x61, 0x79, 0x56, 0x6f, 0x6c, 0x12, 0x2a, 0x0a, 0x10, 0x6f, 0x63,
	0x63, 0x75, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x76, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x10, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x76, 0x67, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x50, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x50, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x6c,
	0x6c, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x61, 0x6c, 0x6c, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x38, 0x0a, 0x09,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x09, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x10, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x51, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x72,
	0x6f, 0x7a, 0x65, 0x6e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x66, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64,
	0x12, 0x32, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x42, 0x0a, 0x5a, 0x08, 0x67, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_position_proto_rawDescOnce sync.Once
	file_common_position_proto_rawDescData = file_common_position_proto_rawDesc
)

func file_common_position_proto_rawDescGZIP() []byte {
	file_common_position_proto_rawDescOnce.Do(func() {
		file_common_position_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_position_proto_rawDescData)
	})
	return file_common_position_proto_rawDescData
}

var file_common_position_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_position_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_position_proto_goTypes = []interface{}{
	(PositionDirection_Enum)(0),        // 0: pb.PositionDirection.Enum
	(PositionChannel_Enum)(0),          // 1: pb.PositionChannel.Enum
	(*GetPositionRequest)(nil),         // 2: pb.GetPositionRequest
	(*GetPositionReply)(nil),           // 3: pb.GetPositionReply
	(*GetStrategyPositionRequest)(nil), // 4: pb.GetStrategyPositionRequest
	(*GetStrategyPositionReply)(nil),   // 5: pb.GetStrategyPositionReply
	(*PositionDirection)(nil),          // 6: pb.PositionDirection
	(*PositionChannel)(nil),            // 7: pb.PositionChannel
	(*Position)(nil),                   // 8: pb.Position
}
var file_common_position_proto_depIdxs = []int32{
	0, // 0: pb.GetPositionRequest.positionDirection:type_name -> pb.PositionDirection.Enum
	8, // 1: pb.GetPositionReply.positions:type_name -> pb.Position
	0, // 2: pb.GetStrategyPositionRequest.positionDirection:type_name -> pb.PositionDirection.Enum
	8, // 3: pb.GetStrategyPositionReply.positions:type_name -> pb.Position
	0, // 4: pb.Position.direction:type_name -> pb.PositionDirection.Enum
	1, // 5: pb.Position.channel:type_name -> pb.PositionChannel.Enum
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_common_position_proto_init() }
func file_common_position_proto_init() {
	if File_common_position_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_position_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPositionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_position_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPositionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_position_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStrategyPositionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_position_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStrategyPositionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_position_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionDirection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_position_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_position_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_position_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_position_proto_goTypes,
		DependencyIndexes: file_common_position_proto_depIdxs,
		EnumInfos:         file_common_position_proto_enumTypes,
		MessageInfos:      file_common_position_proto_msgTypes,
	}.Build()
	File_common_position_proto = out.File
	file_common_position_proto_rawDesc = nil
	file_common_position_proto_goTypes = nil
	file_common_position_proto_depIdxs = nil
}
